#!/bin/bash

#use codesourcery toolchain
TOOLCHAIN_PREFIX="arm-none-eabi-"
export TOOLCHAIN_PREFIX

if [ "$1" = "clean" ]; then
	cd lk 
	make htcleo clean
	cd ..
	rm bin/nbfix	
fi

rm bin/lk.bin
rm bin/os.nb.payload
rm bin/os.nb
rm bin/RUU_signed.nbh



if [ ! -f bin/nbfix ]; then
	gcc nbfix.c -o bin/nbfix
fi

cd lk
make htcleo DEBUG=1
[ $? -eq 0 ] || exit 1
cp build-htcleo/lk.bin ../bin/
cd ..



cd bin
cp template_os.nb.payload os.nb.payload
wine osnbtool.exe -c os.nb.payload 0 lk.bin
mv os.nb.payload.NEW os.nb.payload
./nbfix
wine NBMerge.exe -kaiser os.nb
wine yang.exe -F RUU_signed.nbh -f os.nb -t 0x400 -s 64 -d PB8110000 -c 11111111 -v CLK1.3 -l WWE
cd ..



